version: '3.1'

services:
  db:
    image: mysql:8.0.21
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./docker-data/db-data:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports: 
      - 3306:3306
  adminer:
    depends_on: 
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080